
name: 构建doris-manager Docker镜像

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "doris-manager/Dockerfile"
  repository_dispatch:
    types: doris-manager

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - id: repo_name
        uses: ASzc/change-string-case-action@v1
        with:
          string: ${{ github.repository_owner }}

      - name: 构建并推送到Dockerhub和ghcr.io镜像仓库
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./doris-manager/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            akyakya/doris-manager:latest
